services:
  - type: web
    name: bookbuddy-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node src/server.js
    healthCheckPath: /ping
    autoDeploy: true
