import React from 'react';
import {
  LayoutDashboard,
  Search,
  Library,
  Receipt,
  CreditCard,
  FileText,
  ListPlus,
  Sparkles,
  Award,
  Bookmark,
  Monitor,
  MessageSquare,
  Users,
  ArrowRightLeft,
  BookPlus,
  UploadCloud,
  PackageSearch,
  Settings2,
  DoorOpen,
  Ticket,
  LineChart,
} from 'lucide-react';

export const STUDENT_NAV_ITEMS = [
  {
    key: 'dashboard',
    label: 'Dashboard Home',
    icon: LayoutDashboard,
    route: '/student-dashboard',
    feature: null, // Always enabled
  },
  {
    key: 'catalog',
    label: 'Catalog & Alerts',
    icon: Search,
    route: '/catalog',
    feature: 'catalog',
  },
  {
    key: 'loans',
    label: 'My Borrowing',
    icon: Library,
    route: '/loans',
    feature: 'loans',
  },
  {
    key: 'fines',
    label: 'Fines & Dues',
    icon: Receipt,
    route: '/fines',
    feature: 'fines',
  },
  {
    key: 'patron-card',
    label: 'Patron Card',
    icon: CreditCard,
    route: '/patron-card',
    feature: 'patron-card',
  },
  {
    key: 'e-resources',
    label: 'E-Resources',
    icon: FileText,
    route: '/e-resources',
    feature: 'e-resources',
  },
  {
    key: 'reading-lists',
    label: 'Reading Lists',
    icon: ListPlus,
    route: '/reading-lists',
    feature: 'reading-lists',
  },
  {
    key: 'recommendations',
    label: 'Recommendations',
    icon: Sparkles,
    route: '/recommendations',
    feature: 'recommendations',
  },
  {
    key: 'achievements',
    label: 'Achievements & Streaks',
    icon: Award,
    route: '/achievements',
    feature: 'gamification',
  },
  {
    key: 'saved',
    label: 'Saved & Bookmarks',
    icon: Bookmark,
    route: '/saved',
    feature: 'saved',
  },
  {
    key: 'lab-booking',
    label: 'Lab Booking',
    icon: Monitor,
    route: '/lab-booking',
    feature: 'facilities',
  },
  {
    key: 'support',
    label: 'Support & Helpdesk',
    icon: MessageSquare,
    route: '/support',
    feature: 'support',
  },
];

export const COLLEGE_ADMIN_NAV_ITEMS = [
  {
    key: 'dashboard',
    label: 'Overview Home',
    icon: LayoutDashboard,
    route: '/college-admin',
    feature: null,
  },
  {
    key: 'bulk-upload',
    label: 'Bulk Student Upload',
    icon: UploadCloud,
    route: '/college-admin/bulk-upload',
    feature: null, // Admin feature
  },
  {
    key: 'patrons',
    label: 'Patrons & Roles',
    icon: Users,
    route: '/college-admin/patrons',
    feature: null,
  },
  {
    key: 'circulation',
    label: 'Circulation & Queue',
    icon: ArrowRightLeft,
    route: '/college-admin/circulation',
    feature: 'loans',
  },
  {
    key: 'cataloging',
    label: 'Cataloging',
    icon: BookPlus,
    route: '/college-admin/cataloging',
    feature: 'catalog',
  },
  {
    key: 'digital-assets',
    label: 'Digital Assets',
    icon: UploadCloud,
    route: '/college-admin/digital-assets',
    feature: 'e-resources',
  },
  {
    key: 'inventory',
    label: 'Stock Auditing',
    icon: PackageSearch,
    route: '/college-admin/inventory',
    feature: null,
  },
  {
    key: 'finances',
    label: 'Finances & Ledgers',
    icon: Settings2,
    route: '/college-admin/finances',
    feature: 'fines',
  },
  {
    key: 'system-config',
    label: 'System Config',
    icon: Settings2,
    route: '/college-admin/system-config',
    feature: null,
  },
  {
    key: 'facilities',
    label: 'Facilities',
    icon: DoorOpen,
    route: '/college-admin/facilities',
    feature: 'facilities',
  },
  {
    key: 'helpdesk',
    label: 'Helpdesk',
    icon: Ticket,
    route: '/college-admin/helpdesk',
    feature: 'support',
  },
  {
    key: 'analytics',
    label: 'Analytics',
    icon: LineChart,
    route: '/college-admin/analytics',
    feature: 'analytics',
  },
];
