import {
  LayoutDashboard,
  Search,
  Library,
  Receipt,
  CreditCard,
  FileText,
  ListPlus,
  Sparkles,
  Award,
  Bookmark,
  Monitor,
  MessageSquare,
  Users,
  ArrowRightLeft,
  BookPlus,
  UploadCloud,
  PackageSearch,
  Settings2,
  DoorOpen,
  Ticket,
  LineChart,
} from 'lucide-react';

export const STUDENT_NAV_ITEMS = [
  {
    key: 'dashboard',
    label: 'Dashboard Home',
    icon: LayoutDashboard,
    route: '/student-dashboard',
    feature: null,
  },
  {
    key: 'catalog',
    label: 'Catalog & Alerts',
    icon: Search,
    route: '/catalog',
    feature: 'catalog',
  },
  {
    key: 'loans',
    label: 'My Borrowing',
    icon: Library,
    route: '/loans',
    feature: 'loans',
  },
  {
    key: 'fines',
    label: 'Fines & Dues',
    icon: Receipt,
    route: '/fines',
    feature: 'fines',
  },
  {
    key: 'patron-card',
    label: 'Patron Card',
    icon: CreditCard,
    route: '/patron-card',
    feature: 'patron-card',
  },
  {
    key: 'e-resources',
    label: 'E-Resources',
    icon: FileText,
    route: '/e-resources',
    feature: 'e-resources',
  },
  {
    key: 'reading-lists',
    label: 'Reading Lists',
    icon: ListPlus,
    route: '/reading-lists',
    feature: 'reading-lists',
  },
  {
    key: 'recommendations',
    label: 'Recommendations',
    icon: Sparkles,
    route: '/recommendations',
    feature: 'recommendations',
  },
  {
    key: 'achievements',
    label: 'Achievements & Streaks',
    icon: Award,
    route: '/achievements',
    feature: 'gamification',
  },
  {
    key: 'saved',
    label: 'Saved & Bookmarks',
    icon: Bookmark,
    route: '/saved',
    feature: 'saved',
  },
  {
    key: 'lab-booking',
    label: 'Lab Booking',
    icon: Monitor,
    route: '/lab-booking',
    feature: 'facilities',
  },
  {
    key: 'support',
    label: 'Support & Helpdesk',
    icon: MessageSquare,
    route: '/support',
    feature: 'support',
  },
];

export const COLLEGE_ADMIN_NAV_ITEMS = [
  {
    key: 'dashboard',
    label: 'Provisioned Dashboard',
    icon: LayoutDashboard,
    route: '/college-admin',
    feature: null,
  },
  {
    key: 'features',
    label: 'Add & Manage Features',
    icon: Settings2,
    route: '/college-admin/features',
    feature: null,
  },
  {
    key: 'bulk-upload',
    label: 'Bulk CSV Student Upload',
    icon: UploadCloud,
    route: '/college-admin/bulk-upload',
    feature: null,
  },
];
