import {
  LayoutDashboard,
  Search,
  Library,
  Receipt,
  CreditCard,
  FileText,
  ListPlus,
  Sparkles,
  Award,
  Bookmark,
  Monitor,
  MessageSquare,
  UploadCloud,
  Settings2,
  Share2,
  Megaphone,
  Download,
  Globe,
  Users,
  Building,
  FileCheck,
  Shield,
  Layers,
  HelpCircle,
  FileSearch,
  HardDrive,
  ShoppingBag,
  User,
} from "lucide-react";

export const STUDENT_NAV_ITEMS = [
  {
    key: "dashboard",
    label: "Dashboard Home",
    icon: LayoutDashboard,
    route: "/student",
    feature: null,
  },
  {
    key: "catalog",
    label: "Catalog & Search",
    icon: Search,
    route: "/student/catalog",
    feature: "catalog",
  },
  {
    key: "loans",
    label: "My Borrowing",
    icon: Library,
    route: "/student/loans",
    feature: "loans",
  },
  {
    key: "fines",
    label: "Fines & Dues",
    icon: Receipt,
    route: "/student/fines",
    feature: "fines",
  },
  {
    key: "patron-card",
    label: "Patron Card",
    icon: CreditCard,
    route: "/student/card",
    feature: "patron-card",
  },
  {
    key: "e-resources",
    label: "E-Resources",
    icon: FileText,
    route: "/student/e-resources",
    feature: "e-resources",
  },
  {
    key: "reading-lists",
    label: "Reading Lists",
    icon: ListPlus,
    route: "/student/reading-lists",
    feature: "reading-lists",
  },
  {
    key: "shelves",
    label: "My Shelves",
    icon: Bookmark,
    route: "/student/shelves",
    feature: "readingLists",
  },
  {
    key: "feed",
    label: "Campus Feed",
    icon: Megaphone,
    route: "/student/feed",
    feature: "bulletinBoard",
  },
  {
    key: "cross-college",
    label: "Inter-College",
    icon: Share2,
    route: "/student/cross-college",
    feature: "crossCollegeILL",
  },
  {
    key: "downloads",
    label: "Downloads",
    icon: Download,
    route: "/student/downloads",
    feature: "offlineDownload",
  },
  {
    key: "recommendations",
    label: "Recommendations",
    icon: Sparkles,
    route: "/student/recommendations",
    feature: "recommendations",
  },
  {
    key: "achievements",
    label: "Achievements",
    icon: Award,
    route: "/student/engagement",
    feature: "gamification",
  },
  {
    key: "saved",
    label: "Saved & Bookmarks",
    icon: Bookmark,
    route: "/student/saved",
    feature: "saved",
  },
  {
    key: "lab-booking",
    label: "Lab Booking",
    icon: Monitor,
    route: "/student/facilities",
    feature: "facilities",
  },
  {
    key: "support",
    label: "Support & Helpdesk",
    icon: MessageSquare,
    route: "/student/support",
    feature: "support",
  },
  {
    key: "profile",
    label: "Profile & Settings",
    icon: User,
    route: "/student/profile",
    feature: null,
  },
];

export const COLLEGE_ADMIN_NAV_ITEMS = [
  {
    key: "dashboard",
    label: "Provisioned Dashboard",
    icon: LayoutDashboard,
    route: "/college-admin",
    feature: null,
  },
  {
    key: "features",
    label: "Add & Manage Features",
    icon: Settings2,
    route: "/college-admin/features",
    feature: null,
  },
  {
    key: "bulk-upload",
    label: "Bulk CSV Student Upload",
    icon: UploadCloud,
    route: "/college-admin/bulk-upload",
    feature: null,
  },
  {
    key: "acquisitions",
    label: "Acquisitions Desk",
    icon: ShoppingBag,
    route: "/college-admin/acquisitions",
    feature: "acquisitions",
  },
];

export const SUPER_ADMIN_NAV_ITEMS = [
  {
    key: "overview",
    label: "System Overview",
    icon: Globe,
    route: "/admin-portal/overview",
    feature: null,
  },
  {
    key: "users",
    label: "User Directory",
    icon: Users,
    route: "/admin-portal/users",
    feature: null,
  },
  {
    key: "college-admins",
    label: "College Tenants",
    icon: Building,
    route: "/admin-portal/college-admins",
    feature: null,
  },
  {
    key: "registration-queue",
    label: "Onboarding Queue",
    icon: FileCheck,
    route: "/admin-portal/registration-queue",
    feature: null,
  },
  {
    key: "moderation",
    label: "Content Moderation",
    icon: Shield,
    route: "/admin-portal/moderation",
    feature: null,
  },
  {
    key: "data-oversight",
    label: "Data Oversight",
    icon: Layers,
    route: "/admin-portal/data-oversight",
    feature: null,
  },
  {
    key: "support",
    label: "Support Queue",
    icon: HelpCircle,
    route: "/admin-portal/support",
    feature: null,
  },
  {
    key: "audit-logs",
    label: "Audit Logs",
    icon: FileSearch,
    route: "/admin-portal/audit-logs",
    feature: null,
  },
  {
    key: "settings",
    label: "System Settings",
    icon: HardDrive,
    route: "/admin-portal/settings",
    feature: null,
  },
];

export const GENERAL_NAV_ITEMS = [
  {
    key: "dashboard",
    label: "Dashboard Home",
    icon: LayoutDashboard,
    route: "/general-dashboard",
    feature: null,
  },
  {
    key: "search",
    label: "Advanced Search",
    icon: Search,
    route: "/general-dashboard/search",
    feature: null,
  },
  {
    key: "e-resources",
    label: "Public E-Resources",
    icon: FileText,
    route: "/general-dashboard/e-resources",
    feature: null,
  },
  {
    key: "saved",
    label: "Saved Bookmarks",
    icon: Bookmark,
    route: "/general-dashboard/saved",
    feature: null,
  },
];
