#!/usr/bin/env bash
# ==============================================================================
# BookBuddy Production Secret Loader: fetch-secrets.sh
# Retrieves rotated secrets from Google Cloud Secret Manager and populates
# backend/.env with strict permissions (chmod 600).
#
# Target: GCP Compute Engine Production VM
# Required IAM Role: roles/secretmanager.secretAccessor on VM Service Account
# ==============================================================================

set -euo pipefail

# Output destination
TARGET_ENV_FILE="${1:-backend/.env}"
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
FULL_TARGET_PATH="${PROJECT_DIR}/${TARGET_ENV_FILE}"

echo "========================================================"
echo "🔒 BookBuddy Secret Manager Sync"
echo "Target: ${FULL_TARGET_PATH}"
echo "========================================================"

# Resolve GCP Project ID
if [[ -n "${GCP_PROJECT:-}" ]]; then
  PROJECT_ID="${GCP_PROJECT}"
elif command -v gcloud &>/dev/null; then
  PROJECT_ID="$(gcloud config get-value project 2>/dev/null || true)"
else
  PROJECT_ID=""
fi

# Fallback to Compute Engine metadata service if on GCP VM
if [[ -z "${PROJECT_ID}" ]]; then
  if curl -s -f -H "Metadata-Flavor: Google" "http://metadata.google.internal/computeMetadata/v1/project/project-id" &>/dev/null; then
    PROJECT_ID="$(curl -s -H "Metadata-Flavor: Google" "http://metadata.google.internal/computeMetadata/v1/project/project-id")"
  fi
fi

if [[ -z "${PROJECT_ID}" ]]; then
  echo "❌ Error: Could not determine GCP Project ID. Set GCP_PROJECT or configure gcloud." >&2
  exit 1
fi

echo "✅ Using GCP Project: ${PROJECT_ID}"

# Function to fetch a secret from Secret Manager
get_secret() {
  local secret_name="$1"
  local default_val="${2:-}"
  
  if ! command -v gcloud &>/dev/null; then
    if [[ -n "${default_val}" ]]; then
      echo "${default_val}"
      return 0
    fi
    echo "❌ Error: gcloud CLI not found and no default provided for secret: ${secret_name}" >&2
    return 1
  fi

  local secret_val
  if secret_val="$(gcloud secrets versions access latest --secret="${secret_name}" --project="${PROJECT_ID}" 2>/dev/null)"; then
    echo "${secret_val}"
  elif [[ -n "${default_val}" ]]; then
    echo "${default_val}"
  else
    echo "❌ Error: Required secret '${secret_name}' not found in Secret Manager for project ${PROJECT_ID}" >&2
    return 1
  fi
}

echo "📥 Fetching secrets from Google Secret Manager..."

# Core Application Settings
NODE_ENV="production"
PORT="5000"
HOST="0.0.0.0"
CLIENT_ORIGIN="${CLIENT_ORIGIN:-https://book-buddy-eight-rosy.vercel.app}"
CLIENT_URL="${CLIENT_URL:-https://book-buddy-eight-rosy.vercel.app}"

# Required Secrets
MONGO_URI="$(get_secret "bookbuddy-mongo-uri")"
REDIS_URL="$(get_secret "bookbuddy-redis-url")"
UPSTASH_REDIS_REST_URL="$(get_secret "bookbuddy-upstash-redis-rest-url" "")"
UPSTASH_REDIS_REST_TOKEN="$(get_secret "bookbuddy-upstash-redis-rest-token" "")"
JWT_SECRET="$(get_secret "bookbuddy-jwt-secret")"
JWT_REFRESH_SECRET="$(get_secret "bookbuddy-jwt-refresh-secret")"
JWT_ACCESS_EXPIRY="15m"
JWT_REFRESH_EXPIRY="7d"

# Integration Secrets
GOOGLE_BOOKS_API_KEY="$(get_secret "bookbuddy-google-books-api-key" "")"
GOOGLE_CLIENT_ID="$(get_secret "bookbuddy-google-client-id" "")"
GOOGLE_CLIENT_SECRET="$(get_secret "bookbuddy-google-client-secret" "")"
CLOUDINARY_CLOUD_NAME="$(get_secret "bookbuddy-cloudinary-cloud-name" "")"
CLOUDINARY_API_KEY="$(get_secret "bookbuddy-cloudinary-api-key" "")"
CLOUDINARY_API_SECRET="$(get_secret "bookbuddy-cloudinary-api-secret" "")"
ALGOLIA_APP_ID="$(get_secret "bookbuddy-algolia-app-id" "")"
ALGOLIA_ADMIN_KEY="$(get_secret "bookbuddy-algolia-admin-key" "")"
ALGOLIA_INDEX_NAME="${ALGOLIA_INDEX_NAME:-bookbuddy_books}"
RAZORPAY_KEY_ID="$(get_secret "bookbuddy-razorpay-key-id" "")"
RAZORPAY_KEY_SECRET="$(get_secret "bookbuddy-razorpay-key-secret" "")"
RAZORPAY_WEBHOOK_SECRET="$(get_secret "bookbuddy-razorpay-webhook-secret" "")"
SCANNER_API_KEY="$(get_secret "bookbuddy-scanner-api-key" "bookbuddy_scanner_secret_2026")"
SEED_SUPER_ADMIN_PASSWORD="$(get_secret "bookbuddy-superadmin-seed-password" "")"

# SMTP Settings
SMTP_HOST="$(get_secret "bookbuddy-smtp-host" "")"
SMTP_PORT="$(get_secret "bookbuddy-smtp-port" "587")"
SMTP_USER="$(get_secret "bookbuddy-smtp-user" "")"
SMTP_PASS="$(get_secret "bookbuddy-smtp-pass" "")"
SMTP_FROM="$(get_secret "bookbuddy-smtp-from" "BookBuddy <noreply@bookbuddy.app>")"

# Sentry
SENTRY_DSN="$(get_secret "bookbuddy-sentry-dsn" "")"

# Rate Limiting
RATE_LIMIT_AUTH_IP_MAX="10"
RATE_LIMIT_AUTH_MAX="30"

# Ensure destination directory exists
mkdir -p "$(dirname "${FULL_TARGET_PATH}")"

# Write out secure .env file
cat <<EOF > "${FULL_TARGET_PATH}"
# BookBuddy Production Environment Configuration
# Auto-generated by fetch-secrets.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT COMMIT TO VERSION CONTROL

NODE_ENV=${NODE_ENV}
PORT=${PORT}
HOST=${HOST}
CLIENT_ORIGIN=${CLIENT_ORIGIN}
CLIENT_URL=${CLIENT_URL}

MONGO_URI=${MONGO_URI}
REDIS_URL=${REDIS_URL}
UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}

JWT_SECRET=${JWT_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
JWT_ACCESS_EXPIRY=${JWT_ACCESS_EXPIRY}
JWT_REFRESH_EXPIRY=${JWT_REFRESH_EXPIRY}

GOOGLE_BOOKS_API_KEY=${GOOGLE_BOOKS_API_KEY}
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}

ALGOLIA_APP_ID=${ALGOLIA_APP_ID}
ALGOLIA_ADMIN_KEY=${ALGOLIA_ADMIN_KEY}
ALGOLIA_INDEX_NAME=${ALGOLIA_INDEX_NAME}

RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
RAZORPAY_WEBHOOK_SECRET=${RAZORPAY_WEBHOOK_SECRET}

SCANNER_API_KEY=${SCANNER_API_KEY}
SEED_SUPER_ADMIN_PASSWORD=${SEED_SUPER_ADMIN_PASSWORD}

SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_USER=${SMTP_USER}
SMTP_PASS=${SMTP_PASS}
SMTP_FROM=${SMTP_FROM}

SENTRY_DSN=${SENTRY_DSN}

RATE_LIMIT_AUTH_IP_MAX=${RATE_LIMIT_AUTH_IP_MAX}
RATE_LIMIT_AUTH_MAX=${RATE_LIMIT_AUTH_MAX}
EOF

# Lock down file permissions to read/write by owner only
chmod 600 "${FULL_TARGET_PATH}"

echo "✅ Environment file written successfully to ${FULL_TARGET_PATH} with permissions 0600."
echo "✅ All secrets fetched and verified against Secret Manager."
